site_name: cdflib
theme:
  name: material
repo_url: https://github.com/MAVENSDC/cdflib
nav:
  - Home: index.md
  - API:
    - cdfread: cdfread.md
    - cdfwrite: cdfwrite.md
    - cdfepoch: cdfepoch.md
    - dataclasses: dataclasses.md
    - xarray: xarray.md
  - Changelog: changelog.md
  - Development: development.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
