site_name: cdflib
theme:
  name: material
repo_url: https://github.com/lasp/cdflib
nav:
  - Home: index.md
  - Tools:
    - Reading CDFs: cdfread.md
    - Writing CDFs: cdfwrite.md
    - Time Conversions: cdfepoch.md
    - dataclasses: dataclasses.md
    - xarray: xarray.md
  - XArray Tools: xarray.md
  - Changelog: changelog.md
  - Development: development.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: numpy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
